[package]
name = "spectrix"
version = "0.3.0"
authors = ["Alex Conley <imaconley1@gmail.com>"]
edition = "2021"
rust-version = "1.81.0"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
egui = "0.29.1"
eframe = { version = "0.29.1", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
log = "0.4"

# You only need serde if you want app persistence:
serde = { version = "1.0.210", features = ["derive"] }

egui_plot = {version = "0.29.0", features = ["serde"] }
egui_tiles = "0.10.1"
egui_extras = {version = "0.29.1", features = ["syntect"] }
epaint = "0.29.1"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

# performant will make the compile times slower but should make the histogrammer faster
polars = { version = "0.43.1", features = ["lazy", "parquet", "performant"] }
polars-lazy = { version = "0.43.1", features = ["hist"] }
hashbrown = { version = "=0.14.5", features = ["raw"] } #needed until polars fixes

rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.31"
serde_json = "1.0.128"
geo = "0.28.0"
fnv = "1.0.7"
varpro = "0.10.0"
nalgebra = "0.33.1"
compute = "0.2.3"
indicatif = "0.17"
find_peaks = "0.1.5"
pyo3 = { version = "0.22.5", features = ["auto-initialize"] }
prettytable = "0.10"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.45"

# to access the DOM (to hide the loading text)
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.72"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2


[patch.crates-io]